import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MapContainer,TileLayer,Marker,Popup,Circle,Polyline,useMap} from 'react-leaflet';
import L from 'leaflet';
import {io} from 'socket.io-client';
import 'leaflet/dist/leaflet.css';
import './style.css';

const HANU={lat:20.9902,lng:105.7972};
const RADIUS_M=300, MAP_ZOOM=18.3, MAP_MIN_ZOOM=17.8;
const HANU_VIEW_BOUNDS=[[HANU.lat-0.0035,HANU.lng-0.0045],[HANU.lat+0.004,HANU.lng+0.0045]];
const API=window.location.origin;
const TESTS={
 mid:{label:'Giữa kỳ',female:{distance:400,thresholds:[['10',84],['9',91],['8',97],['7',103],['6',109],['5',115],['4',121],['3',127],['2',133],['1',139],['0',144]]},male:{distance:800,thresholds:[['10',184],['9',191],['8',197],['7',203],['6',209],['5',215],['4',221],['3',227],['2',233],['1',239],['0',244]]}},
 final:{label:'Cuối kỳ',female:{distance:800,thresholds:[['10',210],['9',221],['8',231],['7',241],['6',251],['5',261],['4',271],['3',281],['2',291],['1',301],['0',310]]},male:{distance:1500,thresholds:[['10',360],['9',371],['8',381],['7',391],['6',401],['5',411],['4',421],['3',431],['2',441],['1',451],['0',460]]}}
};
function uid(){let x=localStorage.getItem('hanu_uid');if(!x){x=crypto?.randomUUID?.()||Math.random().toString(36).slice(2);localStorage.setItem('hanu_uid',x)}return x}
const USER_ID=uid();
function distance(a,b){const R=6371000,p=Math.PI/180,dLat=(b.lat-a.lat)*p,dLon=(b.lng-a.lng)*p,x=Math.sin(dLat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x));}
function formatTime(sec){sec=Math.max(0,Math.floor(sec||0));const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function pace(time,meters){if(!meters||meters<20||!time)return '--:--';const p=time/60/(meters/1000);return `${Math.floor(p)}:${String(Math.round((p%1)*60)).padStart(2,'0')}`}
function scoreFor(seconds,test,gender){const cfg=TESTS[test]?.[gender];if(!cfg)return null;const row=cfg.thresholds.find(([,limit])=>seconds<=limit);return row?Number(row[0]):0}
function Recenter({pos}){const map=useMap();useEffect(()=>{if(pos)map.setView([pos.lat,pos.lng],18,{animate:true})},[pos]);return null}
const runnerIcon=()=>L.divIcon({className:'runner-icon',html:'<div class="dot active"></div>',iconSize:[24,24],iconAnchor:[12,12]});
const Icon=({children})=><span className="nav-ico">{children}</span>;

async function json(url,options={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}

function App(){
 const [tab,setTab]=useState('home'),[name,setName]=useState(localStorage.getItem('hanu_name')||'Huy'),[online,setOnline]=useState(true),[boot,setBoot]=useState(null),[error,setError]=useState('');
 const [running,setRunning]=useState(false),[competition,setCompetition]=useState(false),[pos,setPos]=useState(null),[track,setTrack]=useState([]),[distanceRun,setDistanceRun]=useState(0),[seconds,setSeconds]=useState(0),[status,setStatus]=useState('Ready'),[lastRun,setLastRun]=useState(null);
 const [runners,setRunners]=useState([]),[feed,setFeed]=useState([]),[leader,setLeader]=useState([]),[friends,setFriends]=useState([]),[requests,setRequests]=useState([]),[matched,setMatched]=useState(null);
 const distanceRef=useRef(0);
 const [cameraOpen,setCameraOpen]=useState(false),[cameraError,setCameraError]=useState(''),[caption,setCaption]=useState(''),[capture,setCapture]=useState(null);
 const [test,setTest]=useState('final'),[gender,setGender]=useState('male'),[testScore,setTestScore]=useState(null);
 const socketRef=useRef(null),watchRef=useRef(null),lastRef=useRef(null),startRef=useRef(null),videoRef=useRef(null),streamRef=useRef(null),canvasRef=useRef(null),runningRef=useRef(false);
 const runs=boot?.runs||[];
 useEffect(()=>{localStorage.setItem('hanu_name',name)},[name]);
 useEffect(()=>{runningRef.current=running},[running]);
 useEffect(()=>{let alive=true;(async()=>{try{const d=await json(`/api/bootstrap?userId=${encodeURIComponent(USER_ID)}&nickname=${encodeURIComponent(name)}`);if(!alive)return;setBoot(d);setFeed(d.feed||[]);setLeader(d.leaderboard||[]);setFriends(d.friends||[]);setRequests(d.requests||[]);const s=io(API,{transports:['websocket','polling']});socketRef.current=s;s.on('connect',()=>{setOnline(true);s.emit('register',{userId:USER_ID,nickname:name})});s.on('connect_error',()=>setOnline(false));s.on('runners:update',setRunners);s.on('leaderboard:update',setLeader);s.on('feed:update',p=>setFeed(x=>[p,...x.filter(q=>q.id!==p.id)]));s.on('feed:like',({id,likes})=>setFeed(x=>x.map(p=>p.id===id?{...p,likes}:p)));s.on('feed:comment',({postId,comment})=>setFeed(x=>x.map(p=>p.id===postId?{...p,comments:[...(p.comments||[]),comment]}:p)));s.on('friends:update',refresh);return()=>{alive=false;s.disconnect()}}catch(e){setOnline(false);setError(`Server unavailable: ${e.message}`);setBoot({user:{id:USER_ID,nickname:name},friends:[],requests:[],feed:[],leaderboard:[],runners:[],runs:[]})}})();return()=>{if(watchRef.current)navigator.geolocation.clearWatch(watchRef.current);socketRef.current?.disconnect()}},[]);
 const refresh=async()=>{try{const d=await json(`/api/bootstrap?userId=${USER_ID}&nickname=${encodeURIComponent(name)}`);setBoot(d);setFeed(d.feed||[]);setLeader(d.leaderboard||[]);setFriends(d.friends||[]);setRequests(d.requests||[])}catch(e){setError(e.message)}};
 useEffect(()=>{if(!running)return;const t=setInterval(()=>setSeconds(Math.floor((Date.now()-startRef.current)/1000)),1000);return()=>clearInterval(t)},[running]);
 const start=async (comp=false)=>{if(!navigator.geolocation){setStatus('GPS is not supported');return}setError('');setCompetition(comp);setStatus('Requesting GPS…');setSeconds(0);setDistanceRun(0);distanceRef.current=0;setTrack([]);setLastRun(null);setTestScore(null);lastRef.current=null;startRef.current=Date.now();setRunning(true);setTab('run');navigator.geolocation.getCurrentPosition(p=>{const first={lat:p.coords.latitude,lng:p.coords.longitude};setPos(first);setTrack([first]);lastRef.current=first;socketRef.current?.emit('run:start',{lat:first.lat,lng:first.lng,nickname:name,competition:comp});setStatus(distance(HANU,first)<=RADIUS_M?'GPS connected · HANU zone':'GPS connected · outside HANU zone')},e=>setStatus(e.message),{enableHighAccuracy:true,maximumAge:0,timeout:15000});watchRef.current=navigator.geolocation.watchPosition(p=>{const next={lat:p.coords.latitude,lng:p.coords.longitude};let nextDistance=distanceRef.current;if(lastRef.current){const d=distance(lastRef.current,next);if(d<100){nextDistance+=d;distanceRef.current=nextDistance;setDistanceRun(nextDistance)}}lastRef.current=next;setPos(next);setTrack(x=>[...x,next]);socketRef.current?.emit('run:location',{lat:next.lat,lng:next.lng,distance:nextDistance,seconds:Math.floor((Date.now()-startRef.current)/1000),competition:comp});setStatus(distance(HANU,next)<=RADIUS_M?'GPS connected · HANU zone':'Outside HANU zone')},e=>setStatus(e.message),{enableHighAccuracy:true,maximumAge:3000,timeout:10000})};
 const stop=async()=>{if(watchRef.current)navigator.geolocation.clearWatch(watchRef.current);watchRef.current=null;socketRef.current?.emit('run:stop');setRunning(false);const finalSeconds=Math.floor((Date.now()-startRef.current)/1000); const result={distance:distanceRef.current,time:finalSeconds,date:new Date().toISOString(),competition};if(competition){const target=TESTS[test][gender].distance;const reached=distanceRef.current>=target;result.competitionResult={test,gender,distance:target,score:reached?scoreFor(finalSeconds,test,gender):0,targetReached:reached};}setLastRun(result);setCompetition(false);setTestScore(result.competitionResult?.score??null);try{await json('/api/runs',{method:'POST',body:JSON.stringify({userId:USER_ID,nickname:name,distance:result.distance,time:result.time,competition:result.competition,route:track,competitionResult:result.competitionResult||null})});await refresh()}catch(e){setError(`Run saved locally in this screen, but server save failed: ${e.message}`)}};
 const openCamera=async()=>{setCameraError('');setCapture(null);setCameraOpen(true);try{if(!window.isSecureContext&&!['localhost','127.0.0.1'].includes(location.hostname))throw new Error('Camera requires HTTPS or localhost.');if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera API is unavailable.');const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});streamRef.current=stream;requestAnimationFrame(async()=>{if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play()}})}catch(e){setCameraError(e.message||'Could not open camera.')}};
 const closeCamera=()=>{streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setCameraOpen(false);setCapture(null);setCameraError('');setCaption('')};
 const takePhoto=()=>{const v=videoRef.current,c=canvasRef.current;if(!v||!c)return;c.width=v.videoWidth||720;c.height=v.videoHeight||1280;c.getContext('2d').drawImage(v,0,0,c.width,c.height);setCapture(c.toDataURL('image/jpeg',.82));streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null};
 const publishPost=async()=>{if(!capture)return;try{const d=await json('/api/posts',{method:'POST',body:JSON.stringify({userId:USER_ID,nickname:name,text:caption,distance:lastRun?.distance||distanceRun,pace:pace(lastRun?.time||seconds,lastRun?.distance||distanceRun),imageData:capture})});setFeed(x=>[d,...x.filter(p=>p.id!==d.id)]);closeCamera();setTab('community')}catch(e){setCameraError(e.message)}};
 const like=async id=>{try{await json(`/api/posts/${id}/like`,{method:'POST',body:JSON.stringify({userId:USER_ID})})}catch(e){setError(e.message)}};
 const comment=async(id,text)=>{try{await json(`/api/posts/${id}/comment`,{method:'POST',body:JSON.stringify({userId:USER_ID,nickname:name,text})})}catch(e){setError(e.message)}};
 const sendFriend=async to=>{try{await json('/api/friends/request',{method:'POST',body:JSON.stringify({from:USER_ID,to})});setError('Friend request sent.')}catch(e){setError(e.message)}};
 const respond=async(r,accept)=>{try{await json('/api/friends/respond',{method:'POST',body:JSON.stringify({requestId:r.id,userId:USER_ID,accept})});refresh()}catch(e){setError(e.message)}};
 const nav=id=>{if(running&&id!=='run')return;setTab(id)};
 const totalKm=runs.reduce((s,r)=>s+r.distance,0)/1000,totalSec=runs.reduce((s,r)=>s+r.time,0);const nearby=useMemo(()=>runners.filter(r=>r.userId!==USER_ID).map(r=>({...r,meters:distance(pos||HANU,{lat:r.lat,lng:r.lng})})).filter(r=>r.meters<=RADIUS_M).sort((a,b)=>a.meters-b.meters),[runners,pos]);
 const Header=({title,sub})=><header className="page-head"><div><small>{sub}</small><h1>{title}</h1></div><div className="avatar-top">{name[0]?.toUpperCase()||'R'}</div></header>;
 const Bottom=()=> <nav className="bottom-nav">{[['home','⌂','Home'],['progress','◔','Progress'],['run','▶','Run'],['community','▣','Community'],['match','◎','Match']].map(([id,ic,tx])=><button key={id} className={tab===id?'active':''} onClick={()=>nav(id)} disabled={running&&id!=='run'}><Icon>{ic}</Icon><span>{tx}</span></button>)}</nav>;
 if(!boot&&!error)return <div className="loading">Loading HANU Run Tracker…</div>;
 return <div className="app-shell">
  {error&&<div className="toast" onClick={()=>setError('')}>{error} ×</div>}
  {tab==='home'&&<main className="page home"><Header title={`Hi, ${name} 👋`} sub="HANU RUN"/><section className="hero"><div><span className="live-tag">● HANU SPORTS AREA</span><h2>Ready for<br/>your next run?</h2><p>Live GPS, real runners, progress, friends and HANU test mode.</p><button onClick={()=>start(false)}>▶ START RUN</button></div><div className="hero-orbit">🏃</div></section><section className="quick-grid"><button onClick={()=>setTab('progress')}><b>◔</b><span>My progress</span><small>{totalKm.toFixed(1)} km total</small></button><button onClick={()=>setTab('leader')}><b>♛</b><span>Leaderboard</span><small>{leader.length} runners</small></button><button onClick={()=>setTab('match')}><b>◎</b><span>Match runners</span><small>{nearby.length} nearby now</small></button><button onClick={()=>setTab('community')}><b>▣</b><span>Community</span><small>{friends.length} friends</small></button><button className="competition" onClick={()=>setTab('competition')}><b>⚑</b><span>HANU endurance test</span><small>Official thresholds from your table</small></button></section><section className="home-card"><div className="section-row"><h3>My latest activity</h3><button onClick={()=>setTab('progress')}>See all</button></div>{runs[0]?<RunRow run={runs[0]}/>:<div className="blank">Complete a run and it will appear here.</div>}</section><section className="home-card"><div className="section-row"><h3>Running at HANU</h3><span className="online">● {online?'ONLINE':'OFFLINE'}</span></div><div className="campus-live"><strong>{runners.length}</strong><span>runners sharing live location</span></div></section></main>}
  {tab==='run'&&<RunScreen running={running} pos={pos} runners={runners} track={track} distanceRun={distanceRun} seconds={seconds} name={name} setName={setName} status={status} lastRun={lastRun} start={()=>start(false)} stop={stop} competition={competition} onShare={openCamera}/>} 
  {tab==='progress'&&<Progress runs={runs} totalKm={totalKm} totalSec={totalSec} openCamera={openCamera}/>} 
  {tab==='leader'&&<Leaderboard leader={leader} name={name} totalKm={totalKm}/>} 
  {tab==='match'&&<Match nearby={nearby} matched={matched} setMatched={setMatched} start={start} sendFriend={sendFriend}/>} 
  {tab==='community'&&<Community name={name} feed={feed} friends={friends} requests={requests} respond={respond} sendFriend={sendFriend} openCamera={openCamera} like={like} comment={comment}/>} 
  {tab==='competition'&&<Competition test={test} setTest={setTest} gender={gender} setGender={setGender} onStart={()=>start(true)} lastRun={lastRun}/>} 
  {tab!=='run'&&<Bottom/>}
  {cameraOpen&&<CameraModal videoRef={videoRef} canvasRef={canvasRef} capture={capture} error={cameraError} caption={caption} setCaption={setCaption} onCapture={takePhoto} onClose={closeCamera} onPublish={publishPost}/>} 
 </div>
}

function Progress({runs,totalKm,totalSec,openCamera}){return <main className="page"><HeaderStatic title="My progress" sub="YOUR RUNNING"/><section className="summary"><div><small>TOTAL</small><strong>{totalKm.toFixed(2)}<em> km</em></strong></div><div><small>RUNS</small><strong>{runs.length}</strong></div><div><small>TIME</small><strong>{formatTime(totalSec)}</strong></div></section><section className="goal"><div><span>This week's goal</span><b>{Math.min(100,Math.round(totalKm/10*100))}%</b></div><div className="bar"><i style={{width:`${Math.min(100,totalKm/10*100)}%`}}/></div><small>{totalKm.toFixed(1)} / 10 km</small></section><section className="home-card"><div className="section-row"><h3>Run history</h3><button onClick={openCamera}>Post a run</button></div>{runs.length?runs.map(r=><RunRow key={r.id} run={r}/>):<div className="blank">Complete a run and it will appear here.</div>}</section></main>}
function HeaderStatic({title,sub}){return <header className="page-head"><div><small>{sub}</small><h1>{title}</h1></div></header>}
function Leaderboard({leader,name,totalKm}){return <main className="page"><HeaderStatic title="Leaderboard" sub="HANU CAMPUS · LAST 7 DAYS"/><section className="rank-list">{leader.length?leader.map((r,i)=><div key={r.userId}><strong>{i+1}</strong><i>{r.nickname[0]}</i><span><b>{r.nickname}{r.nickname===name?' · You':''}</b><small>{r.runs} run(s) · Avg pace {pace(r.time,r.distance)}/km</small></span><em>{(r.distance/1000).toFixed(2)} km</em></div>):<div className="blank">No runs in the last 7 days.</div>}</section>{!leader.some(r=>r.nickname===name)&&<div className="you-rank-card">You: {totalKm.toFixed(2)} km · complete a run to enter the weekly leaderboard.</div>}</main>}
function Match({nearby,matched,setMatched,start,sendFriend}){return <main className="page"><HeaderStatic title="Match runners" sub="LIVE · OPTED-IN RUNNERS"/>{matched?<section className="match-found"><span>✓ RUNNER FOUND</span><div className="big-face">{matched.nickname[0]}</div><h2>{matched.nickname}</h2><p>{Math.round(matched.meters)} m away · {pace(matched.seconds,matched.distance)}/km</p><button onClick={()=>start(false)}>RUN TOGETHER</button><button className="secondary" onClick={()=>setMatched(null)}>Find another</button><button className="secondary" onClick={()=>sendFriend(matched.userId)}>ADD FRIEND</button></section>:<><section className="radar"><div className="radar-ring r1"/><div className="radar-ring r2"/><div className="radar-ring r3"/><div className="me">YOU</div>{nearby.slice(0,6).map((r,i)=><i key={r.userId} className={`person p${(i%6)+1}`} onClick={()=>setMatched(r)}>{r.nickname[0]}</i>)}</section><section className="home-card"><h3>{nearby.length} runners nearby</h3>{nearby.length?nearby.map(r=><div className="near" key={r.userId}><i>{r.nickname[0]}</i><span><b>{r.nickname}</b><small>{Math.round(r.meters)} m · {pace(r.seconds,r.distance)}/km</small></span><button onClick={()=>setMatched(r)}>MATCH</button></div>):<div className="blank">No opted-in runners within 300 m right now.</div>}</section><p className="demo-note">Only users who are currently running share their live location.</p></>}</main>}
function Community({name,feed,friends,requests,respond,sendFriend,openCamera,like,comment}){const[section,setSection]=useState('feed');return <main className="page community"><HeaderStatic title="Community" sub="HANU RUN CLUB"/><div className="community-tabs"><button className={section==='feed'?'on':''} onClick={()=>setSection('feed')}>Run feed</button><button className={section==='friends'?'on':''} onClick={()=>setSection('friends')}>Friends {requests.length>0&&<b>{requests.length}</b>}</button></div>{section==='feed'?<><section className="post-cta"><div><strong>Share your run</strong><span>Camera only · no gallery uploads</span></div><button onClick={openCamera}>📷 Take photo</button></section><div className="feed">{feed.length?feed.map(post=><Post key={post.id} post={post} name={name} like={like} comment={comment}/>):<div className="blank">No posts yet. Be the first to share a run.</div>}</div></>:<><section className="friend-card"><div className="section-row"><h3>Friend requests</h3><span className="request-badge">{requests.length}</span></div>{requests.length?requests.map(r=><div className="request-row" key={r.id}><i>{r.fromUser.nickname[0]}</i><span><b>{r.fromUser.nickname}</b><small>wants to be your running friend</small></span><button onClick={()=>respond(r,true)}>Accept</button><button className="reject" onClick={()=>respond(r,false)}>Decline</button></div>):<div className="blank">No new friend requests.</div>}</section><section className="friend-card"><h3>Your friends</h3>{friends.length?friends.map(f=><div className="friend-row" key={f.id}><i>{f.nickname[0]}</i><span><b>{f.nickname}</b><small>Friend</small></span><button onClick={()=>sendFriend(f.id)}>INVITE</button></div>):<div className="blank">No friends yet. Match with runners and add them.</div>}</section></>}</main>}
function Post({post,name,like,comment}){const[open,setOpen]=useState(false),[text,setText]=useState('');return <article className="post"><div className="post-head"><i>{post.nickname[0]}</i><span><b>{post.nickname}{post.nickname===name?' · You':''}</b><small>{new Date(post.date).toLocaleString('vi-VN')}</small></span><button>•••</button></div>{post.image&&<img className="post-photo" src={post.image} alt="Run photo"/>}<p>{post.text}</p><div className="post-stats"><span>🏃 <b>{(post.distance/1000).toFixed(2)} km</b></span><span>⚡ <b>{post.pace}</b></span></div><div className="post-actions"><button onClick={()=>like(post.id)}>♥ {post.likes||0}</button><button onClick={()=>setOpen(x=>!x)}>○ {post.comments?.length||0} Comment</button></div>{open&&<div className="comment-box"><div>{(post.comments||[]).map(c=><p key={c.id}><b>{c.nickname}</b> {c.text}</p>)}</div><form onSubmit={e=>{e.preventDefault();if(text.trim())comment(post.id,text);setText('')}}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Write a comment…"/><button>Send</button></form></div>}</article>}
function Competition({test,setTest,gender,setGender,onStart,lastRun}){const cfg=TESTS[test][gender];return <main className="page"><HeaderStatic title="Endurance test" sub="HANU COMPETITION MODE"/><section className="test-hero"><span>⚑ OFFICIAL TABLE</span><h2>HANU endurance test</h2><p>Score is calculated from the time table supplied in this chat.</p></section><section className="rules"><h3>Choose test</h3><div className="seg"><button className={test==='mid'?'on':''} onClick={()=>setTest('mid')}>Giữa kỳ</button><button className={test==='final'?'on':''} onClick={()=>setTest('final')}>Cuối kỳ</button></div><h3>Gender category</h3><div className="seg"><button className={gender==='female'?'on':''} onClick={()=>setGender('female')}>Nữ</button><button className={gender==='male'?'on':''} onClick={()=>setGender('male')}>Nam</button></div><div><b>Distance</b><span>{cfg.distance} m</span></div><div><b>10 điểm</b><span>{formatTime(cfg.thresholds[0][1])}</span></div><div><b>5 điểm</b><span>{formatTime(cfg.thresholds.find(x=>x[0]==='5')[1])}</span></div><div><b>0 điểm</b><span>{formatTime(cfg.thresholds.find(x=>x[0]==='0')[1])} or slower</span></div></section><button className="primary-wide" onClick={onStart}>⚑ START {cfg.distance}M TEST</button>{lastRun?.competition&&<section className="result-card"><b>Latest result</b><strong>{lastRun.competitionResult?.score ?? '—'} / 10</strong><span>{formatTime(lastRun.time)} · {(lastRun.distance/1000).toFixed(2)} km</span></section>}</main>}
function RunRow({run}){return <div className="run-row"><i>🏃</i><span><b>{run.competition?'Competition run':'Outdoor run'}</b><small>{new Date(run.date).toLocaleDateString('vi-VN')} · {formatTime(run.time)}</small></span><em>{(run.distance/1000).toFixed(2)} km<br/><small>{pace(run.time,run.distance)}/km</small></em></div>}
function RunScreen({running,pos,runners,track,distanceRun,seconds,name,setName,status,lastRun,start,stop,competition,onShare}){const inArea=pos?distance(HANU,pos)<=RADIUS_M:null;const d=lastRun?.distance??distanceRun,t=lastRun?.time??seconds,p=pace(t,d);return <main className="run-screen"><div className="map-wrap"><MapContainer center={[HANU.lat,HANU.lng]} zoom={MAP_ZOOM} minZoom={MAP_MIN_ZOOM} maxZoom={19} maxBounds={HANU_VIEW_BOUNDS} maxBoundsViscosity={1} zoomControl={false} className="map"><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><Circle center={[HANU.lat,HANU.lng]} radius={RADIUS_M} pathOptions={{dashArray:'8 8'}}/>{pos&&<Marker position={[pos.lat,pos.lng]} icon={runnerIcon()}><Popup>{name} · You</Popup></Marker>}{runners.filter(r=>r.userId!==USER_ID&&distance(HANU,{lat:r.lat,lng:r.lng})<=RADIUS_M).map(r=><Marker key={r.userId} position={[r.lat,r.lng]} icon={runnerIcon()}><Popup>{r.nickname} · {Math.round(distance(HANU,{lat:r.lat,lng:r.lng}))} m from HANU center</Popup></Marker>)}{track.length>1&&<Polyline positions={track.map(x=>[x.lat,x.lng])}/>}<Recenter pos={pos}/></MapContainer><div className="run-top"><button onClick={()=>!running&&(location.hash='home',location.reload())}>‹</button><span>{competition?'⚑ COMPETITION':'● LIVE RUN'}</span><b>{inArea===false?'OUTSIDE ZONE':'HANU'}</b></div></div><section className="run-panel"><small>{running?'RUNNING NOW':lastRun?'RUN COMPLETE':'READY'}</small><h1>{formatTime(t)}</h1><div className="run-stats"><div><span>DISTANCE</span><b>{(d/1000).toFixed(2)}<small> km</small></b></div><div><span>AVG PACE</span><b>{p}<small> /km</small></b></div></div>{!running&&!lastRun&&<input value={name} onChange={e=>setName(e.target.value)} placeholder="Runner name"/>}<button className={`run-main ${running?'stop':''}`} onClick={running?stop:start}>{running?'■ STOP & FINISH':'▶ START RUN'}</button>{lastRun&&<div className="result"><b>✓ Run saved</b><span>{(d/1000).toFixed(2)} km · {formatTime(t)} · {p}/km</span>{lastRun.competition&&<span>Score: <strong>{lastRun.competitionResult?.score ?? '—'}/10</strong> · {lastRun.competitionResult?.targetReached?'distance reached':'distance not reached'}</span>}<button onClick={onShare}>📷 Share this run</button></div>}<p className="gps-status">{status}</p></section></main>}
function CameraModal({videoRef,canvasRef,capture,error,caption,setCaption,onCapture,onClose,onPublish}){return <div className="camera-overlay"><div className="camera-card"><div className="camera-head"><div><small>CAMERA ONLY</small><h2>New run post</h2></div><button onClick={onClose}>×</button></div>{error?<div className="camera-error">📷 {error}<small>Allow camera permission. This feature has no gallery/file picker.</small></div>:capture?<img className="capture-preview" src={capture} alt="Captured run preview"/>:<video ref={videoRef} className="camera-view" playsInline muted/>}<canvas ref={canvasRef} hidden/><textarea value={caption} onChange={e=>setCaption(e.target.value)} placeholder="Write something about your run…" maxLength={180}/><div className="camera-actions">{!capture&&!error&&<button className="shutter" onClick={onCapture}>●</button>}{capture&&<button onClick={onCapture} className="secondary-cam">Retake</button>}<button className="publish" disabled={!capture} onClick={onPublish}>Post</button></div><p className="camera-note">Only a photo captured directly by the device camera can be posted.</p></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
